name: "Build and Deploy Containerized App"
on:
  push:
    branches:
      - "master"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "cloning the code"
        uses: actions/checkout@v2
      
      - name: "login in docker"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "build and push"
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tag: king100xp/user_app:latest
      
      - name: "verifying pushed image "
        run: docker pull king100xp/user_app:latest
        
      

   
