name: Build and Deploy Containerized App

on:
  push:
    branches:
      - "master"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "cloning the code"
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Save Docker credentials to an Environment File
      - name: Save Docker credentials
        run: echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} | base64)\"}}}" > ~/.docker/config.json

      - name: "build and push"
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tag: king100xp/user_app:latest
      
      - name: "verifying pushed image "
        run: docker pull king100xp/user_app:latest
